### ISSUE TITLE
Layout problem in android browser

### ISSUE THREAD

**Issue by mosprogrammer** [GoogleCloudPlatform/anthos-developer-sandbox#1]
In the morning of today I started using Cloud Shell, but when I touched Terminal, this problem occurred.

![Screenshot_20201115-135402_Chrome](https://user-images.githubusercontent.com/13210738/99178959-52cb0780-274b-11eb-9e9c-7f83ac4aeebf.jpg)

**Comment by di** [comment]
Hi @mosprogrammer, thanks for reporting this. Since this is an issue with Cloud Shell and not with the sandbox itself, I've made an internal issue about it. Thanks again!
